version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.2.7

    steps:
      - checkout
      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
